-- Phase 9: past questions.
--
-- A past-question collection is one uploaded paper (or a bundle of papers):
-- "WAEC Biology 2024", "Anatomy Past Questions 2021–2025". Its file lives in
-- the private `study-materials` bucket, under the same
-- {user_id}/{subject_id}/{id}/{name} layout as study materials, so the
-- storage policies from Phase 3 already protect it.
--
-- Collections are kept apart from study_materials on purpose. They are not
-- chunked or embedded and never appear in the knowledge base, so a tutor
-- answer or a generated quiz is never written from an exam paper by accident.
--
--   past_question_sets ── past_questions
--
-- Every row carries its owner, and the composite foreign key ties a question
-- to a collection with the SAME owner, whatever a client sends.

-- ---------------------------------------------------------------------------
-- past_question_sets
-- ---------------------------------------------------------------------------
create table public.past_question_sets (
  -- Generated by the app before upload so it can be used in the storage path.
  id uuid primary key default gen_random_uuid(),
  -- Filled in from the session. Clients are not granted this column.
  user_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  subject_id uuid not null,
  title text not null,
  -- Everything below is optional: a student is never made to fill it in.
  exam_type text,
  institution text,
  exam_year integer,
  course_code text,
  description text,
  original_filename text not null,
  file_path text not null,
  mime_type text not null,
  file_size bigint not null,
  file_extension text not null,
  -- pending → processing → ready | failed. 'ready' means the file was read;
  -- how many questions were recognised is counted from past_questions.
  processing_status text not null default 'pending',
  processing_error text,
  processing_started_at timestamptz,
  processed_at timestamptz,
  -- Whether Ari has labelled the questions with topics yet.
  analysis_status text not null default 'pending',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint past_question_sets_title_length check (char_length(btrim(title)) between 1 and 150),
  constraint past_question_sets_exam_type_length check (exam_type is null or char_length(exam_type) between 1 and 80),
  constraint past_question_sets_institution_length check (institution is null or char_length(institution) between 1 and 120),
  constraint past_question_sets_exam_year_valid check (exam_year is null or exam_year between 1950 and 2100),
  constraint past_question_sets_course_code_length check (course_code is null or char_length(course_code) between 1 and 40),
  constraint past_question_sets_description_length check (description is null or char_length(description) between 1 and 1000),
  constraint past_question_sets_original_filename_length check (char_length(original_filename) between 1 and 255),
  constraint past_question_sets_file_size_positive check (file_size > 0),
  constraint past_question_sets_file_extension_format check (file_extension ~ '^[a-z0-9]{1,10}$'),
  constraint past_question_sets_processing_status_valid check (processing_status in ('pending', 'processing', 'ready', 'failed')),
  constraint past_question_sets_processing_error_length check (processing_error is null or char_length(processing_error) <= 500),
  constraint past_question_sets_analysis_status_valid check (analysis_status in ('pending', 'partial', 'complete')),
  -- The subject must exist AND belong to the same user. Deleting a subject
  -- removes its collections, as it removes its study materials.
  constraint past_question_sets_subject_owner_fkey
    foreign key (subject_id, user_id) references public.subjects (id, user_id) on delete cascade,
  -- The row can only point at a file inside its own owner/subject/id folder.
  constraint past_question_sets_file_path_owned
    check (starts_with(file_path, user_id::text || '/' || subject_id::text || '/' || id::text || '/')),
  constraint past_question_sets_file_path_key unique (file_path),
  -- Target for foreign keys that must guarantee "same owner".
  constraint past_question_sets_id_user_id_key unique (id, user_id)
);

comment on table public.past_question_sets is 'Uploaded past examination papers. Kept apart from study_materials: never chunked, embedded or searched.';

create index past_question_sets_user_created_idx on public.past_question_sets (user_id, created_at desc);
create index past_question_sets_user_subject_idx on public.past_question_sets (user_id, subject_id);
create index past_question_sets_user_year_idx on public.past_question_sets (user_id, exam_year) where exam_year is not null;

create trigger past_question_sets_set_updated_at
  before update on public.past_question_sets
  for each row execute function public.set_updated_at();

-- ---------------------------------------------------------------------------
-- past_questions
-- ---------------------------------------------------------------------------
create table public.past_questions (
  id uuid primary key default gen_random_uuid(),
  set_id uuid not null,
  user_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  -- Order in the document.
  position integer not null,
  -- As printed: "14", "1a". Null when the paper gave none.
  question_number text,
  question text not null,
  -- 'raw' is text that could not be confidently read as a question. It is
  -- kept exactly as extracted and is never practised or marked.
  question_type text not null,
  -- Multiple choice: the options in the paper's order. Otherwise [].
  options jsonb not null default '[]'::jsonb,
  -- Multiple choice: the correct option's text. True/false: true or false.
  -- Short answer: the expected answer. Null when no answer is known.
  correct_answer jsonb,
  -- Where correct_answer came from. 'official' is the paper's own answer key;
  -- 'ai_generated' is Ari's and is always labelled as such.
  answer_source text not null default 'answer_unavailable',
  explanation text,
  explanation_source text,
  -- The paper's year when a collection spans several; else the collection's.
  exam_year integer,
  -- Null until analysed. 'Uncategorized' when no topic could be named.
  topic text,
  -- Ari's estimate. Null when there is none; never assumed.
  difficulty text,
  analyzed_at timestamptz,
  page_number integer,
  slide_number integer,
  created_at timestamptz not null default now(),

  constraint past_questions_position_valid check (position >= 0),
  constraint past_questions_number_length check (question_number is null or char_length(question_number) between 1 and 12),
  constraint past_questions_question_length check (char_length(question) between 1 and 8000),
  constraint past_questions_type_valid check (question_type in ('multiple_choice', 'true_false', 'short_answer', 'raw')),
  constraint past_questions_options_is_array check (jsonb_typeof(options) = 'array'),
  constraint past_questions_answer_source_valid check (answer_source in ('official', 'ai_generated', 'answer_unavailable')),
  -- An answer always says where it came from, and "unavailable" has none.
  constraint past_questions_answer_matches_source check ((answer_source = 'answer_unavailable') = (correct_answer is null)),
  constraint past_questions_raw_has_no_answer check (question_type <> 'raw' or correct_answer is null),
  constraint past_questions_explanation_length check (explanation is null or char_length(explanation) between 1 and 4000),
  constraint past_questions_explanation_source_valid check (
    (explanation is null and explanation_source is null)
    or (explanation is not null and explanation_source in ('official', 'ai_generated'))
  ),
  constraint past_questions_exam_year_valid check (exam_year is null or exam_year between 1950 and 2100),
  constraint past_questions_topic_length check (topic is null or char_length(topic) between 1 and 80),
  constraint past_questions_difficulty_valid check (difficulty is null or difficulty in ('easy', 'medium', 'hard')),
  constraint past_questions_set_owner_fkey
    foreign key (set_id, user_id) references public.past_question_sets (id, user_id) on delete cascade,
  constraint past_questions_position_key unique (set_id, position),
  constraint past_questions_id_user_id_key unique (id, user_id)
);

comment on table public.past_questions is 'Questions read from a past-question collection. answer_source separates the paper''s own answers from Ari''s.';

-- (set_id, position) is indexed by its unique constraint.
create index past_questions_user_set_idx on public.past_questions (user_id, set_id);
create index past_questions_user_topic_idx on public.past_questions (user_id, topic) where topic is not null;
create index past_questions_user_year_idx on public.past_questions (user_id, exam_year) where exam_year is not null;

-- An answer from the paper's own key is never replaced, and nothing becomes
-- "official" after the fact. Ari's analysis fills in topics and, where the
-- paper gave no answer, a labelled answer of its own; this keeps the two from
-- ever being confused, whatever sends the update.
create function public.protect_official_past_answers()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  if old.answer_source = 'official'
     and (new.answer_source <> 'official' or new.correct_answer is distinct from old.correct_answer) then
    raise exception 'An official answer cannot be changed' using errcode = '42501';
  end if;
  if new.answer_source = 'official' and old.answer_source <> 'official' then
    raise exception 'An answer cannot be marked official after upload' using errcode = '42501';
  end if;
  if old.explanation_source = 'official'
     and (new.explanation_source is distinct from 'official' or new.explanation is distinct from old.explanation) then
    raise exception 'An official explanation cannot be changed' using errcode = '42501';
  end if;
  if new.explanation_source = 'official' and old.explanation_source is distinct from 'official' then
    raise exception 'An explanation cannot be marked official after upload' using errcode = '42501';
  end if;
  return new;
end;
$$;

create trigger past_questions_protect_official
  before update on public.past_questions
  for each row execute function public.protect_official_past_answers();

-- ---------------------------------------------------------------------------
-- Row Level Security: users can only see and change their own rows.
-- ---------------------------------------------------------------------------
alter table public.past_question_sets enable row level security;
alter table public.past_questions enable row level security;

create policy "Users can view their own past question sets"
  on public.past_question_sets for select to authenticated
  using ((select auth.uid()) = user_id);

create policy "Users can add past question sets to their own subjects"
  on public.past_question_sets for insert to authenticated
  with check (
    (select auth.uid()) = user_id
    and exists (
      select 1 from public.subjects s
      where s.id = past_question_sets.subject_id and s.user_id = (select auth.uid())
    )
  );

create policy "Users can update their own past question sets"
  on public.past_question_sets for update to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

create policy "Users can delete their own past question sets"
  on public.past_question_sets for delete to authenticated
  using ((select auth.uid()) = user_id);

create policy "Users can view their own past questions"
  on public.past_questions for select to authenticated
  using ((select auth.uid()) = user_id);

create policy "Users can add questions to their own past question sets"
  on public.past_questions for insert to authenticated
  with check (
    (select auth.uid()) = user_id
    and exists (
      select 1 from public.past_question_sets s
      where s.id = past_questions.set_id and s.user_id = (select auth.uid())
    )
  );

create policy "Users can update their own past questions"
  on public.past_questions for update to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

create policy "Users can delete their own past questions"
  on public.past_questions for delete to authenticated
  using ((select auth.uid()) = user_id);

-- Column-level privileges underneath RLS. Signed-out requests get nothing.
--   * user_id is never writable: it always comes from auth.uid().
--   * A collection's file and subject are fixed once it is uploaded.
--   * A question's wording, options, number and position are fixed once it is
--     read from the paper. Only what analysis adds can be updated, and the
--     trigger above keeps official answers out of reach even then.
revoke all on public.past_question_sets, public.past_questions from anon, authenticated;

grant select, delete on public.past_question_sets to authenticated;
grant insert (id, subject_id, title, exam_type, institution, exam_year, course_code, description,
              original_filename, file_path, mime_type, file_size, file_extension)
  on public.past_question_sets to authenticated;
grant update (title, exam_type, institution, exam_year, course_code, description,
              processing_status, processing_error, processing_started_at, processed_at, analysis_status)
  on public.past_question_sets to authenticated;

grant select, delete on public.past_questions to authenticated;
grant insert (set_id, position, question_number, question, question_type, options, correct_answer, answer_source,
              explanation, explanation_source, exam_year, page_number, slide_number)
  on public.past_questions to authenticated;
grant update (correct_answer, answer_source, explanation, explanation_source, topic, difficulty, analyzed_at)
  on public.past_questions to authenticated;
