-- Phase 6: quizzes.
--
-- A quiz is a set of questions Ari generated from a student's own study
-- materials. A student can take a quiz several times; each time is an
-- attempt, and an attempt holds one answer per question.
--
--   quizzes ─┬─ quiz_questions ─┐
--            └─ quiz_attempts ──┴─ quiz_answers
--
-- Every row carries its owner. Composite foreign keys tie each row to a
-- parent with the SAME owner, so ownership cannot be mixed anywhere in the
-- tree, whatever a client sends.

-- Target for foreign keys that must guarantee "this material belongs to this
-- user" without also naming its subject.
alter table public.study_materials
  add constraint study_materials_id_user_id_key unique (id, user_id);

-- ---------------------------------------------------------------------------
-- quizzes
-- ---------------------------------------------------------------------------
create table public.quizzes (
  id uuid primary key default gen_random_uuid(),
  -- Filled in from the session. Clients are not granted this column.
  user_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  -- What the quiz was generated from. Null subject means "All subjects";
  -- null material means every material in scope. Deleting either keeps the
  -- quiz (its questions are already written) and clears the link.
  subject_id uuid,
  material_id uuid,
  title text not null,
  -- 'quiz' is one the student set up; 'practice' is a quick session.
  mode text not null default 'quiz',
  difficulty text not null,
  question_count integer not null,
  question_types text[] not null,
  created_at timestamptz not null default now(),

  constraint quizzes_title_length check (char_length(btrim(title)) between 1 and 150),
  constraint quizzes_mode_valid check (mode in ('quiz', 'practice')),
  constraint quizzes_difficulty_valid check (difficulty in ('easy', 'medium', 'hard', 'mixed')),
  constraint quizzes_question_count_valid check (question_count between 1 and 20),
  constraint quizzes_question_types_valid check (
    cardinality(question_types) between 1 and 3
    and question_types <@ array['multiple_choice', 'true_false', 'short_answer']
  ),
  constraint quizzes_subject_owner_fkey
    foreign key (subject_id, user_id)
    references public.subjects (id, user_id) on delete set null (subject_id),
  constraint quizzes_material_owner_fkey
    foreign key (material_id, user_id)
    references public.study_materials (id, user_id) on delete set null (material_id),
  constraint quizzes_id_user_id_key unique (id, user_id)
);

comment on table public.quizzes is 'Quizzes generated by Ari from a student''s own study materials.';

create index quizzes_user_created_idx on public.quizzes (user_id, created_at desc);
create index quizzes_subject_idx on public.quizzes (subject_id) where subject_id is not null;
create index quizzes_material_idx on public.quizzes (material_id) where material_id is not null;

-- ---------------------------------------------------------------------------
-- quiz_questions
-- ---------------------------------------------------------------------------
create table public.quiz_questions (
  id uuid primary key default gen_random_uuid(),
  quiz_id uuid not null,
  user_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  position integer not null,
  question text not null,
  question_type text not null,
  -- Multiple choice: the four options in display order. Otherwise [].
  options jsonb not null default '[]'::jsonb,
  -- Multiple choice: the correct option's text. True/false: true or false.
  -- Short answer: the expected answer.
  correct_answer jsonb not null,
  explanation text not null,
  -- The passage the question was written from, as [{ n, materialId, title,
  -- subject, page, slide, section }]. Copied from the knowledge base.
  sources jsonb not null default '[]'::jsonb,
  -- { topic, difficulty, acceptablePoints, sourceExcerpt }
  metadata jsonb not null default '{}'::jsonb,

  constraint quiz_questions_type_valid check (question_type in ('multiple_choice', 'true_false', 'short_answer')),
  constraint quiz_questions_position_valid check (position >= 0),
  constraint quiz_questions_question_length check (char_length(question) between 1 and 2000),
  constraint quiz_questions_explanation_length check (char_length(explanation) between 1 and 4000),
  constraint quiz_questions_options_is_array check (jsonb_typeof(options) = 'array'),
  constraint quiz_questions_sources_is_array check (jsonb_typeof(sources) = 'array'),
  constraint quiz_questions_metadata_is_object check (jsonb_typeof(metadata) = 'object'),
  constraint quiz_questions_quiz_owner_fkey
    foreign key (quiz_id, user_id)
    references public.quizzes (id, user_id) on delete cascade,
  constraint quiz_questions_position_key unique (quiz_id, position),
  -- Target for quiz_answers: an answer's question must be in the same quiz
  -- as its attempt, and have the same owner.
  constraint quiz_questions_id_quiz_user_key unique (id, quiz_id, user_id)
);

comment on table public.quiz_questions is 'Questions of a quiz, with the correct answer and the source each was written from.';

-- (quiz_id, position) is indexed by its unique constraint.
create index quiz_questions_user_idx on public.quiz_questions (user_id);

-- ---------------------------------------------------------------------------
-- quiz_attempts
-- ---------------------------------------------------------------------------
create table public.quiz_attempts (
  id uuid primary key default gen_random_uuid(),
  quiz_id uuid not null,
  user_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  -- Null until the attempt is completed. A correct answer scores 1 and a
  -- partially correct short answer 0.5.
  score numeric(5, 1),
  total_questions integer not null,
  started_at timestamptz not null default now(),
  completed_at timestamptz,

  constraint quiz_attempts_total_valid check (total_questions between 1 and 20),
  constraint quiz_attempts_score_valid check (score is null or (score >= 0 and score <= total_questions)),
  constraint quiz_attempts_quiz_owner_fkey
    foreign key (quiz_id, user_id)
    references public.quizzes (id, user_id) on delete cascade,
  constraint quiz_attempts_id_quiz_user_key unique (id, quiz_id, user_id)
);

comment on table public.quiz_attempts is 'One sitting of a quiz by its owner.';

create index quiz_attempts_quiz_started_idx on public.quiz_attempts (quiz_id, started_at desc);
create index quiz_attempts_user_completed_idx on public.quiz_attempts (user_id, completed_at desc);

-- ---------------------------------------------------------------------------
-- quiz_answers
-- ---------------------------------------------------------------------------
create table public.quiz_answers (
  id uuid primary key default gen_random_uuid(),
  attempt_id uuid not null,
  question_id uuid not null,
  quiz_id uuid not null,
  user_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  -- What the student answered: option text, true/false, or their own words.
  answer jsonb not null,
  is_correct boolean not null,
  -- 'partial' is only possible for short answers.
  result text not null,
  -- { feedback } from the short-answer evaluator; {} otherwise.
  evaluation jsonb not null default '{}'::jsonb,
  answered_at timestamptz not null default now(),

  constraint quiz_answers_result_valid check (result in ('correct', 'partial', 'incorrect')),
  constraint quiz_answers_result_matches check (is_correct = (result = 'correct')),
  constraint quiz_answers_evaluation_is_object check (jsonb_typeof(evaluation) = 'object'),
  -- Together these guarantee the attempt and the question belong to the same
  -- quiz and the same user as the answer.
  constraint quiz_answers_attempt_fkey
    foreign key (attempt_id, quiz_id, user_id)
    references public.quiz_attempts (id, quiz_id, user_id) on delete cascade,
  constraint quiz_answers_question_fkey
    foreign key (question_id, quiz_id, user_id)
    references public.quiz_questions (id, quiz_id, user_id) on delete cascade,
  -- One answer per question per attempt. Answers are final.
  constraint quiz_answers_once_key unique (attempt_id, question_id)
);

comment on table public.quiz_answers is 'A student''s answer to one question in one attempt, with how it was marked.';

create index quiz_answers_question_idx on public.quiz_answers (question_id);
create index quiz_answers_user_answered_idx on public.quiz_answers (user_id, answered_at desc);

-- ---------------------------------------------------------------------------
-- Completing an attempt
-- ---------------------------------------------------------------------------
-- The score is worked out here, from the stored answers, rather than being
-- written by the client. Users have no privilege to update an attempt
-- directly. Unanswered questions score nothing. Completing twice returns the
-- first result unchanged.
--
-- Runs as the function owner (security definer) because of that missing
-- privilege. It acts on the caller's own attempt only: the owner is always
-- auth.uid(), never an argument. search_path is empty and every object is
-- schema-qualified.
create function public.complete_quiz_attempt(p_attempt_id uuid)
returns public.quiz_attempts
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user uuid := auth.uid();
  v_attempt public.quiz_attempts;
begin
  if v_user is null then
    raise exception 'Not authenticated' using errcode = '42501';
  end if;

  select * into v_attempt
    from public.quiz_attempts a
   where a.id = p_attempt_id and a.user_id = v_user
     for update;

  if not found then
    return null;
  end if;
  if v_attempt.completed_at is not null then
    return v_attempt;
  end if;

  update public.quiz_attempts a
     set completed_at = now(),
         total_questions = (select count(*) from public.quiz_questions q where q.quiz_id = a.quiz_id),
         score = coalesce((
           select sum(case s.result when 'correct' then 1 when 'partial' then 0.5 else 0 end)
             from public.quiz_answers s
            where s.attempt_id = a.id
         ), 0)
   where a.id = p_attempt_id and a.user_id = v_user
  returning * into v_attempt;

  return v_attempt;
end;
$$;

revoke execute on function public.complete_quiz_attempt(uuid) from public, anon;
grant execute on function public.complete_quiz_attempt(uuid) to authenticated;

-- ---------------------------------------------------------------------------
-- Row Level Security: users can only see and add to their own rows.
-- ---------------------------------------------------------------------------
alter table public.quizzes enable row level security;
alter table public.quiz_questions enable row level security;
alter table public.quiz_attempts enable row level security;
alter table public.quiz_answers enable row level security;

create policy "Users can view their own quizzes" on public.quizzes for select to authenticated using ((select auth.uid()) = user_id);
create policy "Users can create their own quizzes" on public.quizzes for insert to authenticated with check ((select auth.uid()) = user_id);
create policy "Users can delete their own quizzes" on public.quizzes for delete to authenticated using ((select auth.uid()) = user_id);

create policy "Users can view their own quiz questions" on public.quiz_questions for select to authenticated using ((select auth.uid()) = user_id);
create policy "Users can add questions to their own quizzes" on public.quiz_questions for insert to authenticated with check ((select auth.uid()) = user_id);

create policy "Users can view their own quiz attempts" on public.quiz_attempts for select to authenticated using ((select auth.uid()) = user_id);
create policy "Users can start attempts at their own quizzes" on public.quiz_attempts for insert to authenticated with check ((select auth.uid()) = user_id);

create policy "Users can view their own quiz answers" on public.quiz_answers for select to authenticated using ((select auth.uid()) = user_id);
create policy "Users can answer in their own attempts" on public.quiz_answers for insert to authenticated with check (
  (select auth.uid()) = user_id
  -- A completed attempt takes no more answers.
  and exists (
    select 1 from public.quiz_attempts a
    where a.id = quiz_answers.attempt_id
      and a.user_id = (select auth.uid())
      and a.completed_at is null
  )
);

-- Column-level privileges underneath RLS. Signed-out requests get nothing.
-- Nothing here can be updated: questions and answers are final, and an
-- attempt's score is set only by complete_quiz_attempt(). Questions, attempts
-- and answers are removed only together with their quiz, by the cascade.
revoke all on public.quizzes, public.quiz_questions, public.quiz_attempts, public.quiz_answers from anon, authenticated;

grant select, delete on public.quizzes to authenticated;
grant insert (subject_id, material_id, title, mode, difficulty, question_count, question_types) on public.quizzes to authenticated;

grant select on public.quiz_questions to authenticated;
grant insert (quiz_id, position, question, question_type, options, correct_answer, explanation, sources, metadata) on public.quiz_questions to authenticated;

grant select on public.quiz_attempts to authenticated;
grant insert (quiz_id, total_questions) on public.quiz_attempts to authenticated;

grant select on public.quiz_answers to authenticated;
grant insert (attempt_id, question_id, quiz_id, answer, is_correct, result, evaluation) on public.quiz_answers to authenticated;
