-- Phase 6: flashcards.
--
-- A deck is a set of cards Ari generated from a student's own study
-- materials. Each time the student rates a card (Again / Hard / Good / Easy)
-- a review is recorded. Reviews are only stored for now: they are the data a
-- later spaced-repetition schedule will be built on.
--
--   flashcard_decks ── flashcards ── flashcard_reviews
--
-- As with quizzes, every row carries its owner and composite foreign keys
-- tie each row to a parent with the same owner.

-- ---------------------------------------------------------------------------
-- flashcard_decks
-- ---------------------------------------------------------------------------
create table public.flashcard_decks (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  -- What the deck was generated from. Deleting either keeps the deck.
  subject_id uuid,
  material_id uuid,
  title text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint flashcard_decks_title_length check (char_length(btrim(title)) between 1 and 150),
  constraint flashcard_decks_subject_owner_fkey
    foreign key (subject_id, user_id)
    references public.subjects (id, user_id) on delete set null (subject_id),
  constraint flashcard_decks_material_owner_fkey
    foreign key (material_id, user_id)
    references public.study_materials (id, user_id) on delete set null (material_id),
  constraint flashcard_decks_id_user_id_key unique (id, user_id)
);

comment on table public.flashcard_decks is 'Flashcard decks generated by Ari from a student''s own study materials.';

create index flashcard_decks_user_updated_idx on public.flashcard_decks (user_id, updated_at desc);
create index flashcard_decks_subject_idx on public.flashcard_decks (subject_id) where subject_id is not null;
create index flashcard_decks_material_idx on public.flashcard_decks (material_id) where material_id is not null;

create trigger flashcard_decks_set_updated_at
  before update on public.flashcard_decks
  for each row execute function public.set_updated_at();

-- ---------------------------------------------------------------------------
-- flashcards
-- ---------------------------------------------------------------------------
create table public.flashcards (
  id uuid primary key default gen_random_uuid(),
  deck_id uuid not null,
  user_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  position integer not null,
  front text not null,
  back text not null,
  -- The passage the card was written from, as { n, materialId, title,
  -- subject, page, slide, section }, or null. Copied from the knowledge base.
  source jsonb,
  difficulty text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint flashcards_position_valid check (position >= 0),
  constraint flashcards_front_length check (char_length(front) between 1 and 1000),
  constraint flashcards_back_length check (char_length(back) between 1 and 2000),
  constraint flashcards_source_is_object check (source is null or jsonb_typeof(source) = 'object'),
  constraint flashcards_difficulty_valid check (difficulty is null or difficulty in ('easy', 'medium', 'hard')),
  constraint flashcards_deck_owner_fkey
    foreign key (deck_id, user_id)
    references public.flashcard_decks (id, user_id) on delete cascade,
  constraint flashcards_position_key unique (deck_id, position),
  constraint flashcards_id_user_id_key unique (id, user_id)
);

comment on table public.flashcards is 'Cards of a flashcard deck, with the source each was written from.';

-- (deck_id, position) is indexed by its unique constraint.
create index flashcards_user_idx on public.flashcards (user_id);

create trigger flashcards_set_updated_at
  before update on public.flashcards
  for each row execute function public.set_updated_at();

-- ---------------------------------------------------------------------------
-- flashcard_reviews
-- ---------------------------------------------------------------------------
create table public.flashcard_reviews (
  id uuid primary key default gen_random_uuid(),
  flashcard_id uuid not null,
  user_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  rating text not null,
  reviewed_at timestamptz not null default now(),

  constraint flashcard_reviews_rating_valid check (rating in ('again', 'hard', 'good', 'easy')),
  constraint flashcard_reviews_card_owner_fkey
    foreign key (flashcard_id, user_id)
    references public.flashcards (id, user_id) on delete cascade
);

comment on table public.flashcard_reviews is 'Each time a student rated a flashcard. The history a spaced-repetition schedule will use.';

create index flashcard_reviews_card_reviewed_idx on public.flashcard_reviews (flashcard_id, reviewed_at desc);
create index flashcard_reviews_user_reviewed_idx on public.flashcard_reviews (user_id, reviewed_at desc);

-- ---------------------------------------------------------------------------
-- Keep the deck's updated_at current, so recently studied decks come first
-- ---------------------------------------------------------------------------
-- Runs as the function owner (security definer) because users have no
-- privilege to write updated_at. It only touches the deck of the card that
-- was just reviewed, which the foreign keys have already tied to the same
-- owner, and it cannot be called directly.
create function public.touch_flashcard_deck()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  update public.flashcard_decks d
     set updated_at = now()
    from public.flashcards c
   where c.id = new.flashcard_id
     and c.user_id = new.user_id
     and d.id = c.deck_id
     and d.user_id = new.user_id;
  return null;
end;
$$;

revoke execute on function public.touch_flashcard_deck() from public, anon, authenticated;

create trigger flashcard_reviews_touch_deck
  after insert on public.flashcard_reviews
  for each row execute function public.touch_flashcard_deck();

-- ---------------------------------------------------------------------------
-- Row Level Security: users can only see and change their own rows.
-- ---------------------------------------------------------------------------
alter table public.flashcard_decks enable row level security;
alter table public.flashcards enable row level security;
alter table public.flashcard_reviews enable row level security;

create policy "Users can view their own decks" on public.flashcard_decks for select to authenticated using ((select auth.uid()) = user_id);
create policy "Users can create their own decks" on public.flashcard_decks for insert to authenticated with check ((select auth.uid()) = user_id);
create policy "Users can update their own decks" on public.flashcard_decks for update to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy "Users can delete their own decks" on public.flashcard_decks for delete to authenticated using ((select auth.uid()) = user_id);

create policy "Users can view their own flashcards" on public.flashcards for select to authenticated using ((select auth.uid()) = user_id);
create policy "Users can add cards to their own decks" on public.flashcards for insert to authenticated with check ((select auth.uid()) = user_id);

create policy "Users can view their own reviews" on public.flashcard_reviews for select to authenticated using ((select auth.uid()) = user_id);
create policy "Users can review their own flashcards" on public.flashcard_reviews for insert to authenticated with check ((select auth.uid()) = user_id);

-- Column-level privileges underneath RLS. Signed-out requests get nothing.
-- Owners and timestamps are never writable through the API. Cards and reviews
-- are removed only together with their deck, by the cascade.
revoke all on public.flashcard_decks, public.flashcards, public.flashcard_reviews from anon, authenticated;

grant select, delete on public.flashcard_decks to authenticated;
grant insert (subject_id, material_id, title) on public.flashcard_decks to authenticated;
grant update (title) on public.flashcard_decks to authenticated;

grant select on public.flashcards to authenticated;
grant insert (deck_id, position, front, back, source, difficulty) on public.flashcards to authenticated;

grant select on public.flashcard_reviews to authenticated;
grant insert (flashcard_id, rating) on public.flashcard_reviews to authenticated;
