-- Phase 3: study materials.
--
-- One row per uploaded file. The file itself lives in the private
-- `study-materials` storage bucket at file_path. Rows start as 'pending';
-- Phase 4 will extract text and move them to 'processing' / 'ready' / 'failed'.

create table public.study_materials (
  -- Generated by the app before upload so it can be used in the storage path.
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  subject_id uuid not null,
  title text not null,
  original_filename text not null,
  file_path text not null,
  mime_type text not null,
  file_size bigint not null,
  file_extension text,
  processing_status text not null default 'pending',
  processing_error text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  -- The subject must exist AND belong to the same user. Because the foreign
  -- key includes user_id, a material can never be attached to another user's
  -- subject, whatever the client sends. Deleting a subject removes its rows.
  constraint study_materials_subject_owner_fkey
    foreign key (subject_id, user_id) references public.subjects (id, user_id) on delete cascade,

  constraint study_materials_title_not_empty check (char_length(btrim(title)) between 1 and 150),
  constraint study_materials_original_filename_length check (char_length(original_filename) between 1 and 255),
  constraint study_materials_file_size_positive check (file_size > 0),
  constraint study_materials_file_extension_format check (file_extension ~ '^[a-z0-9]{1,10}$'),
  constraint study_materials_processing_status_valid
    check (processing_status in ('pending', 'processing', 'ready', 'failed')),
  -- The row can only point at a file inside its own owner/subject/material
  -- folder, so a row can never reference somebody else's file.
  constraint study_materials_file_path_owned
    check (starts_with(file_path, user_id::text || '/' || subject_id::text || '/' || id::text || '/')),
  constraint study_materials_file_path_key unique (file_path)
);

comment on table public.study_materials is 'Uploaded study files. processing_status is advanced by the Phase 4 pipeline.';

create index study_materials_user_id_idx on public.study_materials (user_id, created_at desc);
create index study_materials_subject_id_idx on public.study_materials (subject_id);
create index study_materials_user_subject_idx on public.study_materials (user_id, subject_id);
create index study_materials_processing_status_idx on public.study_materials (processing_status);

create trigger study_materials_set_updated_at
  before update on public.study_materials
  for each row execute function public.set_updated_at();

-- ---------------------------------------------------------------------------
-- Row Level Security
-- ---------------------------------------------------------------------------
alter table public.study_materials enable row level security;

create policy "Users can view their own materials"
  on public.study_materials for select
  to authenticated
  using ((select auth.uid()) = user_id);

-- Inserts and updates also check that the subject belongs to the caller. The
-- composite foreign key above already guarantees it; the policy states the
-- rule where ownership rules are expected to live.
create policy "Users can add materials to their own subjects"
  on public.study_materials for insert
  to authenticated
  with check (
    (select auth.uid()) = user_id
    and exists (
      select 1 from public.subjects s
      where s.id = study_materials.subject_id and s.user_id = (select auth.uid())
    )
  );

create policy "Users can update their own materials"
  on public.study_materials for update
  to authenticated
  using ((select auth.uid()) = user_id)
  with check (
    (select auth.uid()) = user_id
    and exists (
      select 1 from public.subjects s
      where s.id = study_materials.subject_id and s.user_id = (select auth.uid())
    )
  );

create policy "Users can delete their own materials"
  on public.study_materials for delete
  to authenticated
  using ((select auth.uid()) = user_id);

-- Column-level privileges underneath RLS.
--   * user_id is never writable: it always comes from auth.uid().
--   * processing_status / processing_error are not writable by users, so every
--     upload starts as 'pending' and only the server-side pipeline changes it.
--   * After upload, the only thing a user can change is the display title.
revoke all on public.study_materials from anon, authenticated;
grant select, delete on public.study_materials to authenticated;
grant insert (id, subject_id, title, original_filename, file_path, mime_type, file_size, file_extension)
  on public.study_materials to authenticated;
grant update (title) on public.study_materials to authenticated;
